dotmesh-io/dotmesh

kubernetes/rebuild.sh
Add AKS manifest changes. Dependent PR here - https://github.com/dotmesh-io/docs/pull/69
=> Add AKS manifest

.gitlab-ci.yml, cmd/dotmesh-server/rpc.go, pkg/fsm/fsm.go, pkg/fsm/fsm_active.go, pkg/fsm/fsm_missing.go, pkg/types/BUILD.bazel, pkg/types/fork.go, tests/fork_test.go
Dotmesh side bug fix for https://github.com/dotmesh-io/gateway/issues/97. The issue was wrong order of operations, less than 10% of fork requests would result in a success. Other forks would be missing metadata or whole commits.
=> 97 fork bugs

cmd/dotmesh-server/controller.go, cmd/dotmesh-server/etcd.go, cmd/dotmesh-server/rpc.go, cmd/dotmesh-server/utils.go, pkg/fsm/fsm.go, pkg/store/kvdb.go, tests/acceptance_test.go
Closes https://github.com/dotmesh-io/dotmesh/issues/635
See issue for details.
There's two changes here - one to try and improve deletion robustness, one to add a fault injection mechanism to test it. It might be clearer to look at the two separate commits than the fused changes view in the PR thing, which conflates the two.
=> 635 deletion

pkg/archiver/BUILD.bazel, pkg/archiver/tar.go, pkg/archiver/tar_test.go, pkg/archiver/utils.go, pkg/fsm/BUILD.bazel, pkg/fsm/fsm.go, pkg/fsm/fsm_active_file_io.go, pkg/fsm/fsm_active_file_io_test.go, tests/BUILD.bazel, tests/s3api_test.go
* Issue: https://github.com/dotmesh-io/dotmesh/issues/639 
* Pipeline passing https://gitlab.dotmesh.com/dotmesh/dotmesh-sync/pipelines/17451
=> Feature directory read

pkg/client/api.go
This is _probably_ the commit that broke push
=> pull in get transfer change

pkg/zfs/exec_util.go, pkg/zfs/zfs.go
Pipeline: https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/19255
=> Zfs retries

pkg/fsm/s3.go
=> #686: limit the number of files to 100, and make breadth first

cmd/dotmesh-server/controller.go, cmd/dotmesh-server/docker.go, cmd/dotmesh-server/rpc.go, pkg/fsm/fsm.go, pkg/registry/registry.go
Pipeline: https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/19533
=> Reduce logging n cleanup

tests/s3api_test.go
Pipeline: https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/19620
=> Fixes for s3 list test

cmd/dotmesh-server/controller.go, cmd/dotmesh-server/replication.go, cmd/dotmesh-server/types.go, cmd/dotmesh-server/utils.go, pkg/fsm/fsm_push_initiator.go, pkg/fsm/prelude.go
=> #700: remove duplicate code and make preludes empty to start with

cmd/dm/pkg/commands/utils.go, pkg/client/api.go, pkg/client/client.go, pkg/client/remotes.go, pkg/types/fsm_types.go
pipeline: https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/19713
=> Poll transfer fixes

cmd/dotmesh-server/diff_handlers.go, cmd/dotmesh-server/http.go, pkg/client/api.go
in diff API call, groundwork for dotscience-agent#158
Pipeline: https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/19812
=> dotscience-agent#158: support specifying snapshot 

pkg/zfs/exec_util.go, pkg/zfs/zfs.go
Pipeline: https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/20271
=> recreate cmd

pkg/client/api.go
Part of dotmesh-io/gateway#205
=> gateway#205: add s3 transfer method

pkg/client/api.go
part of dotmesh-io/gateway#205
=> gateway#205: provide s3 creation at client level

pkg/client/api.go
=> Revert "gateway#205: provide s3 creation at client level"

pkg/fsm/fsm.go, pkg/fsm/s3.go, pkg/types/fsm_types.go
Part of dotmesh-io/frontend-ng#657
=> Pre calculation for s3 transfers

cmd/dotmesh-server/rpc.go, pkg/fsm/fsm.go, pkg/fsm/fsm_missing.go, pkg/fsm/fsm_s3_pull_initiator.go, pkg/fsm/s3.go, pkg/types/fsm_types.go
- make s3 dots always have a commit where they start from missing
- use aws internal retry logic to retry broken parts a few times
=> S3 improvements

pkg/fsm/fsm.go, pkg/fsm/s3.go, pkg/types/fsm_types.go, pkg/types/types.go
part of dotmesh-io/frontend-ng#657
=> NFC: multiball mode

pkg/fsm/s3.go
otherwise things waiting on transfer status will think everything is ok
=> FIX: remove s3 stuck message and make it error

pkg/fsm/s3.go
Part of dotmesh-io/gateway#408
=> dotmesh-io/gateway#408: make a dir if the filepath ends in a slash

.gitlab-ci.yml, pkg/zfs/zfs.go, pkg/zfs/zfs_test.go
Fixes #776.
This was originally part of work on a different issue (#766), but that needed tests, and the tests found a bug. So will do that other issue in a new branch.
=> #776: Basic tests and bug fix for zfs diff

cmd/dotmesh-server/controller.go
don't need to fail to fill in serverStates/serverStatuses if globalDirtyCache is not filled in for this fs
=> hopefully reduce instances of "Got no master state"

cmd/dotmesh-server/s3_handlers.go
I originally added this logging to help me diagnose some issues, but I reckon that logging error details for S3 requests (and some summary information for successful requests) is probably a good thing to have in master by default!
=> S3 logging

pkg/zfs/zfs.go, pkg/zfs/zfs_test.go
Fixes #781 
We need this to work so that Jupyter auto-shutdown works.
=> #781: test zfs.LastModified

cmd/dotmesh-server/http.go, cmd/dotmesh-server/s3_handlers.go, pkg/fsm/fsm_active.go, pkg/fsm/fsm_active_file_io.go, pkg/types/fsm_types.go, pkg/types/types.go, tests/s3api_test.go
=> #773: s3 delete API for dotmesh

pkg/fsm/fsm_discovering.go, pkg/fsm/fsm_missing.go, pkg/fsm/fsm_pull_initiator.go, pkg/fsm/fsm_push_initiator.go
Fixes #788 
If end-to-end tests pass, another candidate for @lukemarsden to test.
https://gitlab.dotmesh.com/dotmesh/dotmesh/pipelines/27672
=> #788: Before we transition to active, make sure we finish snapshotting.

pkg/registry/registry_test.go, pkg/user/external.go, pkg/user/user_test.go, tests/Gopkg.lock, tests/vendor/github.com/dotmesh-io/citools/testtools.go
I needed to add retry logic, so that dotmesh wouldn't have quite so much trouble if it starts before the gateway is ready. Also found that I'd broken some tests before and not noticed, so I fixed that!
=> 793 pluggable authz retries
